site_name: Just Another Blog

theme:
  name: material
  favicon: assets/favicon.svg
  logo: assets/logo.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - content.code.copy
    - content.code.annotate
    - navigation.top
  font:
    text: Crimson Pro
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - abbr
  - admonition
  - footnotes
  - md_in_html
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 


extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - tags:
      tags_file: tags.md
  - search

nav:
  - 'Algorithms':
    - 'algorithms/searching.md'
    - 'algorithms/sorting.md'
    - 'algorithms/partitioning.md'
  - 'Projects':
    - 'projects/tree-printing.md'
  - 'Languages':
    - 'languages/go.md'
  - 'Guides':
    - 'guides/ntfs.md'