site_name: listless 💤
theme:
  name: material
  logo: assets/tired.svg
  favicon: assets/fatigue-dark.svg
  font:
    text: PT Sans
    code: Source Code Pro Medium
  features:
    - content.code.copy
    - content.code.annotate
  # Setup for theme switch https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
plugins:
   - glightbox

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - assets/extra.css

nav:
- About: 'index.md'
- Data Structures:
  - Numbers:
    - Representation: 'data-structures/numbers/representation.md'
    - Arithmetic: 'data-structures/numbers/arithmetic.md'
  - Linked List:
    - Basics: 'data-structures/linked-list/basics.md'
    - Reversing linked list: 'data-structures/linked-list/reverse.md'
  - Heap: 'data-structures/heap/index.md'
  - Circular list: 'data-structures/linear/circular-list.md'
  - Graph:
    - Intro: 'data-structures/graph/intro.md'
    - Traversal:
        - Generic Search: 'data-structures/graph/generic-search.md'
        - BFS: 'data-structures/graph/bfs.md'
        - DFS: 'data-structures/graph/dfs.md'
    - Topological Sort: 'graph/topological-sort.md'
- Algorithms:
  - Binary Search: 'data-structures/search/binary.md'
  - Partitioning: 'data-structures/partition/partition.md'
  - Sorting:
    - Quicksort: 'data-structures/sort/quicksort.md'
    - Mergesort: 'data-structures/sort/mergesort.md'
- JS: 
  - Types: 'js/types.md'
  - Objects:
    - Basics: 'js/object-basics.md'
- Concurrency:
  - Intro: 'concurrency/intro.md'
- Java:
  - Collections: 'java/collections-framework.md'
- Kotlin:
  - Concurrency: 'kt/concurrency.md'
- Android:
  - Activities: 'android/activities.md'
  - Tasks: 'android/tasks.md'
  - Fragments: 'android/fragments.md'
  - Animations: 'android/animation-transition.md'
- Python:
  - Basics: 'python/basics.md'
  - Operators: 'python/operators.md'
  - Structure: 'python/structure.md'
  - Objects: 'python/objects.md'
- Ubuntu:
  - Setup: 'ubuntu/setup.md'
- Miscellaneous:
  - Display Upgrade: 'misc/display.md'



