site_name: listless 💤
theme:
  name: material
  logo: assets/fatigue-light.svg
  favicon: assets/fatigue-dark.svg
  font:
    text: "Briskpace"
    code: "Mullet"
    # code: "Roboto Mono Medium"
  features:
    - content.code.copy
    - content.code.annotate
    - content.tooltips
  # Setup for theme switch https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
plugins:
  - glightbox
  - placeholder:
      placeholder_file: placeholder-plugin.yaml

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - abbr
  - attr_list
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - assets/extra.css

nav:
  - About: "index.md"
  - Blog:
      - Books:
          - Ghost Radio: "blog/books/ghost-radio.md"
          - The Institute: "blog/books/the-institute.md"
          - The Reaping: "blog/books/the-reaping.md"
          - The Hobbit: "blog/books/the-hobbit.md"
  - Maths:
      - Algebra:
          - Numbers: "maths/algebra/numbers.md"
          - Proof √2 is irrational: "maths/algebra/sqrt-2-irrational.md"
          - Laws of arithmetics: "maths/algebra/arithmetic-laws.md"
          - Exponent and logarithmic identities: "maths/algebra/exponent-and-logarithmic-identities.md"
          - Changing base: "maths/algebra/base-change.md"
          - Algebraic expressions: "maths/algebra/expressions.md"
          - Modular arithmetic: "maths/algebra/modulo.md"
          - Complex numbers: "maths/algebra/complex.md"
      - Combinatorics:
          - Sets: "maths/combinatorics/sets.md"
          - Permutation and Combination: "maths/combinatorics/p-and-c.md"
          - Probability: "maths/combinatorics/probability.md"
      - Series: "maths/series.md"
      - Calculus:
          - Functions: "maths/calculus/functions.md"
  - Algorithms:
      - Binary Search: "algorithms/search/binary.md"
      - Partitioning: "algorithms/partition/partition.md"
      - Sorting:
          - Comparison Sorts: "algorithms/sort/comparison.md"
          - Bubble sort: "algorithms/sort/bubble-sort.md"
          - Insertion sort: "algorithms/sort/insertion-sort.md"
          - Selection sort: "algorithms/sort/selection-sort.md"
          - Heapsort: "algorithms/sort/heapsort.md"
          - Quicksort: "algorithms/sort/quicksort.md"
          - Merge Sort: "algorithms/sort/mergesort.md"
          - Counting Sort: "algorithms/sort/counting-sort.md"
      - Divide & Conquer:
          - The Master Method: "algorithms/divide-and-conquer/master-method.md"
      - Dynamic Programming:
          - Intro: "algorithms/dynamic-programming/intro.md"
          - Rod cutting: "algorithms/dynamic-programming/rod-cutting.md"
          - Longest common subsequence: "algorithms/dynamic-programming/longest-common-subsequence.md"
          - Longest common substring: "algorithms/dynamic-programming/longest-common-substring.md"
          - Longest palindromic subsequence: "algorithms/dynamic-programming/longest-palindromic-subsequence.md"
      - Greedy:
          - Huffman coding: "algorithms/greedy/huffman-coding.md"
  - Data Structures:
      - Numbers:
          - Representation: "data-structures/numbers/representation.md"
          - Bit tricks: "data-structures/numbers/bit-tricks.md"
          - Addition Subtraction: "data-structures/numbers/addition.md"
      - Linked List:
          - Singly Linked List: "data-structures/linked-list/singly-linked-list.md"
          - Doubly Linked List: "data-structures/linked-list/doubly-linked-list.md"
          - Common Patterns: "data-structures/linked-list/patterns.md"
      - Array:
          - Problems:
              - "The Dutch National Flag Problem": "data-structures/array/problems/dutch-national-flag.md"
      - Stack:
          - Basics: "data-structures/stack/basics.md"
      - Heap: "data-structures/heap/index.md"
      - Disjoint Set: "data-structures/disjoint-set/index.md"
      - Circular list: "data-structures/circular-list.md"
      - Tree:
          - Traversal:
              - DFS:
                  - Inorder: "data-structures/tree/traversal/inorder-tree-traversal.md"
                  - Preorder: "data-structures/tree/traversal/preorder-tree-traversal.md"
                  - Postorder: "data-structures/tree/traversal/postorder-tree-traversal.md"
              - BFS / level-order: "data-structures/tree/traversal/level-traversal.md"
      - Trie:
          - Introduction: "data-structures/trie/intro.md"
          - Compressed Trie: "data-structures/trie/compressed-trie.md"
      - Graph:
          - Intro: "data-structures/graph/intro.md"
          - Traversal:
              - Generic Search: "data-structures/graph/traversal/generic-search.md"
              - BFS: "data-structures/graph/traversal/bfs.md"
              - DFS: "data-structures/graph/traversal/dfs.md"
          - Topological Sort: "data-structures/graph/topological-sort.md"
          - Single-Source Shortest Paths:
              - Introduction: "data-structures/graph/single-source-shortest-paths/intro.md"
              - Bellman-Ford Algorithm: "data-structures/graph/single-source-shortest-paths/bellman-ford.md"
              - Dijkstra's Algorithm: "data-structures/graph/single-source-shortest-paths/dijkstra.md"
              - SSSP in DAG: "data-structures/graph/single-source-shortest-paths/dag.md"
          - All-Pairs Shortest Paths:
              - Floyd-Warshall Algorithm: "data-structures/graph/all-pairs-shortest-paths/floyd-warshall.md"
          - Minimum Spanning Tree:
              - Introduction: "data-structures/graph/minimum-spanning-tree/intro.md"
              - Kruskal's Algorithm: "data-structures/graph/minimum-spanning-tree/kruskal.md"
              - Prim's Algorithm: "data-structures/graph/minimum-spanning-tree/prim.md"
  - Practice:
      - Learnings: "practice/index.md"
      - Greedy (7):
          - <span class="problem-index"><span>1. </span>Activity selection</span>: "practice/greedy/01-activity-selection.md"
          - <span class="problem-index"><span>2. </span>Huffman Coding</span>: "practice/greedy/02-huffman-coding.md"
          - <span class="problem-index"><span>3. </span>Shortest superstring</span>: "practice/greedy/03-shortest-superstring.md"
          - <span class="problem-index"><span>4. </span>Job sequencing</span>: "practice/greedy/04-job-sequencing.md"
          - <span class="problem-index"><span>5. </span>Graph coloring</span>: "practice/greedy/05-graph-coloring.md"
          - <span class="problem-index"><span>6. </span>Kruskal's algorithm</span>: "practice/greedy/06-kruskal-algorithm.md"
          - <span class="problem-index"><span>7. </span>Prim's algorithm</span>: "practice/greedy/07-prim-algorithm.md"
      - Trie (1):
          - <span class="problem-index"><span>1. </span>Longest Common Prefix</span>: "practice/trie/01-longest-common-prefix.md"
      - Backtracking (10):
          - About: "practice/backtracking/about.md"
          - <span class="problem-index"><span>1. </span>List all binary strings generated from wildcard pattern</span>: "practice/backtracking/01-list-all-binary-strings-generated-from-wildcard-pattern.md"
          - <span class="problem-index"><span>2. </span>Print all possible solutions to N-Queens problem</span>: "practice/backtracking/02-print-possible-solutions-n-queens-problem.md"
          - <span class="problem-index"><span>3. </span>Print all possible Knight's tours</span>: "practice/backtracking/03-print-possible-knights-tours-chessboard.md"
          - <span class="problem-index"><span>4. </span>Find the shortest path in a maze</span>: "practice/backtracking/04-find-shortest-path-in-maze.md"
          - <span class="problem-index"><span>5. </span>Find the shortest path in a maze</span>: "practice/backtracking/05-find-longest-path-in-maze.md"
          - <span class="problem-index"><span>6. </span>Find number of unique paths in a maze</span>: "practice/backtracking/06-find-number-of-unique-paths-in-a-maze.md"
          - <span class="problem-index"><span>7. </span>List all Hamiltonian paths</span>: "practice/backtracking/07-list-all-hamiltonian-paths.md"
          - <span class="problem-index"><span>8. </span>List all k-Colorings</span>: "practice/backtracking/08-list-all-k-colorings.md"
          - <span class="problem-index"><span>9. </span>Split list into k-partitions of equal sum</span>: "practice/backtracking/09-split-list-into-k-partitions-of-equal-sum.md"
          - <span class="problem-index"><span>10. </span>Find ways to calculate a target from elements of the specified array</span>: "practice/backtracking/10-find-ways-calculate-target-elements-array.md"
      - Stack (9):
          - <span class="problem-index"><span>1. </span>Check if a given expression is balanced or not</span>: "practice/stack/01-check-if-a-given-expression-is-balanced-or-not.md"
          - <span class="problem-index"><span>2. </span>Convert infix expression to postfix</span>: "practice/stack/02-convert-infix-expression-to-postfix.md"
          - <span class="problem-index"><span>3. </span>Decode increment decrement sequence</span>: "practice/stack/03-decode-increment-decrement-sequence.md"
          - <span class="problem-index"><span>4. </span>Design a stack that supports peeking minimum element</span>: "practice/stack/04-design-a-stack-that-supports-peeking-minimum-element.md"
          - <span class="problem-index"><span>5. </span>Evaluate postfix expression</span>: "practice/stack/05-evaluate-postfix-expression.md"
          - <span class="problem-index"><span>6. </span>Find duplicate parenthesis in an expression</span>: "practice/stack/06-find-duplicate-parenthesis-in-an-expression.md"
          - <span class="problem-index"><span>7. </span>Inorder tree traversal</span>: "practice/stack/07-inorder-tree-traversal.md"
          - <span class="problem-index"><span>8. </span>Postorder tree traversal</span>: "practice/stack/08-postorder-tree-traversal.md"
          - <span class="problem-index"><span>9. </span>Preorder tree traversal</span>: "practice/stack/09-preorder-tree-traversal.md"
      - Bits (11):
          - <span class="problem-index"><span>1. </span>Find the only non-duplicate number in an array</span>: "practice/bits/01-find-the-only-non-duplicate.md"
          - <span class="problem-index"><span>2. </span>Count the number of set bits</span>: "practice/bits/02-count-the-number-of-set-bits.md"
          - <span class="problem-index"><span>3. </span>Computing the parity of a word</span>: "practice/bits/03-compute-parity.md"
          - <span class="problem-index"><span>4. </span>Swap bits: "practice/bits/04-swap-bits.md"
          - <span class="problem-index"><span>5. </span>Closest integer with same number of set bits</span>: "practice/bits/05-closest-integer-with-same-bit-count.md"
          - <span class="problem-index"><span>6. </span>Add two integers without arithmetic operators</span>: "practice/bits/06-add-two-integers-without-arithmetic-operator.md"
          - <span class="problem-index"><span>7. </span>Multiply two integers without arithmetic operators</span>: "practice/bits/07-multiply-two-integers-without-arithmetic-operator.md"
          - <span class="problem-index"><span>8. </span>Divide two integers without arithmetic operators</span>: "practice/bits/08-divide-two-integers-without-arithmetic-operator.md"
          - <span class="problem-index"><span>9. </span>Calculate exponent of an integer</span>: "practice/bits/09-calculate-exponent-of-an-integer.md"
          - <span class="problem-index"><span>10. </span>Rotate an integer</span>: "practice/bits/10-rotate-an-integer.md"
          - <span class="problem-index"><span>11. </span>Generate random numbers</span>: "practice/bits/11-random-number-generation.md"
      - Linked List (18):
          - <span class="problem-index"><span>1. </span>Check if the content of a linked list is a palindrome</span>: "practice/linked-list/01-check-if-the-content-of-a-linked-list-is-a-palindrome.md"
          - <span class="problem-index"><span>2. </span>Check if two given linked lists are identical</span>: "practice/linked-list/02-check-if-two-given-linked-lists-are-identical.md"
          - <span class="problem-index"><span>3. </span>Create a queue from a linked list</span>: "practice/linked-list/03-create-a-queue-from-a-linked-list.md"
          - <span class="problem-index"><span>4. </span>Create a stack from a linked list</span>: "practice/linked-list/04-create-a-stack-from-a-linked-list.md"
          - <span class="problem-index"><span>5. </span>Deep copy a linked list</span>: "practice/linked-list/05-deep-copy-a-linked-list.md"
          - <span class="problem-index"><span>6. </span>Detect cycle in a linked list</span>: "practice/linked-list/06-detect-cycle-in-a-linked-list.md"
          - <span class="problem-index"><span>7. </span>Get kth node from either end</span>: "practice/linked-list/07-get-kth-node-from-either-end.md"
          - <span class="problem-index"><span>8. </span>In-place merge two sorted linked list</span>: "practice/linked-list/08-in-place-merge-two-sorted-linked-list.md"
          - <span class="problem-index"><span>9. </span>In-place merge arbitrary number of sorted linked list</span>: "practice/linked-list/09-in-place-merge-arbitrary-number-of-sorted-linked-list.md"
          - <span class="problem-index"><span>10. </span>In-place sort a linked list</span>: "practice/linked-list/10-in-place-sort-a-linked-list.md"
          - <span class="problem-index"><span>11. </span>Insert a node in its correct place in a sorted linked list</span>: "practice/linked-list/11-insert-a-node-in-its-correct-place-in-a-sorted-linked-list.md"
          - <span class="problem-index"><span>12. </span>Intersection of two sorted linked list</span>: "practice/linked-list/12-intersection-of-two-sorted-linked-list.md"
          - <span class="problem-index"><span>13. </span>Intersection of two linked lists</span>: "practice/linked-list/13-intersection-of-linked-lists.md"
          - <span class="problem-index"><span>14. </span>Remove duplicates from sorted linked list</span>: "practice/linked-list/14-remove-duplicates-from-sorted-linked-list.md"
          - <span class="problem-index"><span>15. </span>Reverse a linked list in-place</span>: "practice/linked-list/15-reverse-a-linked-list-in-place.md"
          - <span class="problem-index"><span>16. </span>Reverse every group of k nodes</span>: "practice/linked-list/16-reverse-every-group-of-k-nodes.md"
          - <span class="problem-index"><span>17. </span>Split linked list in first and second halves</span>: "practice/linked-list/17-split-linked-list-in-first-and-second-halves.md"
          - <span class="problem-index"><span>18. </span>Turn a linked list Iterable</span>: "practice/linked-list/18-turn-a-linked-list-iterable.md"
      - Sorting (1):
          - <span class="problem-index"><span>1. </span>Merge overlapping intervals</span>: "practice/sorting/01-merge-overlapping-intervals.md"
      - String (1):
          - <span class="problem-index"><span>1. </span>Longest Common Prefix</span>: "practice/string/01-longest-common-prefix.md"
      - Miscellaneous (1):
          - <span class="problem-index"><span>1. </span>Generate Specified Row of Pascal's Triangle</span>: "practice/misc/01-generate-pascals-triangle-row.md"
  - Labs:
      - Tree Printer: "labs/tree-printer.md"
      - Tree Printer v2: "labs/tree-printer-2.md"
      - Huffman Encoder: "labs/huffman-encoding/index.md"
  - Design Patterns:
      - Creational:
          - Singleton: "design-patterns/singleton.md"
          - Builder: "design-patterns/builder.md"
  - Concurrency:
      - Intro: "concurrency/intro.md"
  - Java:
      - Collections: "java/collections-framework.md"
      - Iterators: "java/iterators.md"
  - Kotlin:
      - Concurrency: "kt/concurrency.md"
  - Go:
      - Tour: "go/structure.md"
      - Constants: "go/constants.md"
      - Basic Types: "go/basic-types.md"
      - Aggregate Types: "go/aggregate-types.md"
      - Reference Types:
          - Pointers, Slices and, Map: "go/reference-types.md"
          - Interfaces: "go/interfaces.md"
          - Functions: "go/functions.md"
      - Generics: "go/generics.md"
  - Android:
      - Activities: "android/activities.md"
      - Tasks: "android/tasks.md"
      - Fragments: "android/fragments.md"
      - State Restoration: "android/state-restoration.md"
      - ViewModel: "android/viewmodel.md"
      - Animations: "android/animation-transition.md"
  - Javascript:
      - Objects:
          - Basics: "js/objects/basics.md"
          - Prototype: "js/objects/prototype.md"
          - this: "js/objects/this.md"
  - CSS:
      - Box Model: "css/box-model.md"
      - em, rem, and more: "css/relative-units.md"
  - Python:
      - Basics: "python/basics.md"
      - Operators: "python/operators.md"
      - Structure: "python/structure.md"
      - Objects: "python/objects.md"
      - Functions: "python/functions.md"
      - Generators: "python/generators.md"
      - Object Oriented Programming: "python/oop.md"
  - Ubuntu:
      - Static IP: "ubuntu/static-ip.md"
      - NTFS mount: "ubuntu/ntfs-mount.md"
      - Transmission: "ubuntu/transmission.md"
      - Samba: "ubuntu/samba.md"
  - Snippets:
      - gradle: "snippets/gradle.md"
  - How To:
      - Use 3p ink with Brother printer: "howto/printer-3p-ink.md"
  - Miscellaneous:
      - Display Upgrade: "misc/display.md"
      - yt-dlp: "misc/yt-dlp.md"
