site_name: Just Another Blog
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.svg
  font:
    text: Zilla Slab
    code: Ubuntu Mono
  features:
    - content.code.copy
    - navigation.expand
  # Setup for theme switch https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - assets/extra.css

nav:
- About: 'index.md'
- Graph:
  - About: 'graph/about.md'
  - Breadth-first Search: 'graph/breadth-first-search.md'
  - Depth-first Search: 'graph/depth-first-search.md'
  - Topological Sort: 'graph/topological-sort.md'
- JS: 
  - Basics: 'js/basics.md'
  - Object: 'js/object.md'
