site_name: listless 💤
theme:
  name: material
  logo: assets/fatigue-light.svg
  favicon: assets/fatigue-dark.svg
  font:
    text: "Briskpace"
    code: "Roboto Mono Medium"
  features:
    - content.code.copy
    - content.code.annotate
    - content.tooltips
  # Setup for theme switch https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
plugins:
  - glightbox
  - placeholder:
      placeholder_file: placeholder-plugin.yaml

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - abbr
  - attr_list
  - footnotes

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - assets/extra.css

nav:
  - About: "index.md"
  - Blog:
      - Books:
          - Ghost Radio: "blog/books/ghost-radio.md"
          - The Institute: "blog/books/the-institute.md"
          - The Reaping: "blog/books/the-reaping.md"
          - The Hobbit: "blog/books/the-hobbit.md"
  - Maths:
      - Algebra:
          - Numbers: "maths/numbers.md"
          - Laws of arithmetics: "maths/arithmetic-laws.md"
          - Exponent and logarithmic identities: "maths/exponent-and-logarithmic-identities.md"
          - Changing base: "maths/base-change.md"
          - Algebraic expressions: "maths/expressions.md"
          - Modular arithmetic: "maths/modulo.md"
      - Sets: "maths/sets.md"
  - Data Structures:
      - Numbers:
          - Representation: "data-structures/numbers/representation.md"
          - Arithmetic: "data-structures/numbers/arithmetic.md"
      - Linked List:
          - Singly Linked List: "data-structures/linked-list/singly-linked-list.md"
          - Doubly Linked List: "data-structures/linked-list/doubly-linked-list.md"
          - Problems:
              - Readme: "data-structures/linked-list/problems/readme.md"
              - Turn linked list iterable: "data-structures/linked-list/problems/iterable.md"
              - Reversing linked list: "data-structures/linked-list/problems/reverse.md"
              - Linked list as Stack: "data-structures/linked-list/problems/stack-as-linked-list.md"
              - Linked list as Queue: "data-structures/linked-list/problems/queue-as-linked-list.md"
              - Iterate over list: "data-structures/linked-list/problems/iterate.md"
              - Compare linked lists: "data-structures/linked-list/problems/equality.md"
              - Clone linked lists: "data-structures/linked-list/problems/clone.md"
              - Merge linked lists: "data-structures/linked-list/problems/merge.md"
              - Cycle detection: "data-structures/linked-list/problems/cycle-detection.md"
      - Stack:
          - Basics: "data-structures/stack/basics.md"
      - Heap: "data-structures/heap/index.md"
      - Circular list: "data-structures/circular-list.md"
      - Graph:
          - Intro: "data-structures/graph/intro.md"
          - Traversal:
              - Generic Search: "data-structures/graph/generic-search.md"
              - BFS: "data-structures/graph/bfs.md"
              - DFS: "data-structures/graph/dfs.md"
          - Topological Sort: "data-structures/graph/topological-sort.md"
  - Algorithms:
      - Binary Search: "algorithms/search/binary.md"
      - Partitioning: "algorithms/partition/partition.md"
      - Sorting:
          - Quicksort: "algorithms/sort/quicksort.md"
          - Mergesort: "algorithms/sort/mergesort.md"
          - Counting Sort: "algorithms/sort/counting-sort.md"
  - Design Patterns:
      - Creational:
          - Singleton: "design-patterns/singleton.md"
          - Builder: "design-patterns/builder.md"
  - Concurrency:
      - Intro: "concurrency/intro.md"
  - Java:
      - Collections: "java/collections-framework.md"
      - Iterators: "java/iterators.md"
  - Kotlin:
      - Concurrency: "kt/concurrency.md"
  - Go:
      - Tour: "go/structure.md"
      - Constants: "go/constants.md"
      - Basic Types: "go/basic-types.md"
      - Aggregate Types: "go/aggregate-types.md"
      - Reference Types:
          - Pointers, Slices and, Map: "go/reference-types.md"
          - Interfaces: "go/interfaces.md"
          - Functions: "go/functions.md"
      - Generics: "go/generics.md"
  - Android:
      - Activities: "android/activities.md"
      - Tasks: "android/tasks.md"
      - Fragments: "android/fragments.md"
      - Animations: "android/animation-transition.md"
  - Javascript:
      - Objects:
          - Basics: "js/objects/basics.md"
          - Prototype: "js/objects/prototype.md"
          - this: "js/objects/this.md"
  - CSS:
      - Box Model: "css/box-model.md"
      - em, rem, and more: "css/relative-units.md"
  - Python:
      - Basics: "python/basics.md"
      - Operators: "python/operators.md"
      - Structure: "python/structure.md"
      - Objects: "python/objects.md"
      - Functions: "python/functions.md"
      - Generators: "python/generators.md"
      - Object Oriented Programming: "python/oop.md"
  - Ubuntu:
      - Static IP: "ubuntu/static-ip.md"
      - NTFS mount: "ubuntu/ntfs-mount.md"
      - Transmission: "ubuntu/transmission.md"
      - Samba: "ubuntu/samba.md"
  - Miscellaneous:
      - Display Upgrade: "misc/display.md"
      - yt-dlp: "misc/yt-dlp.md"
