site_name: listless 💤
theme:
  name: material
  logo: assets/fatigue-light.svg
  favicon: assets/fatigue-dark.svg
  font:
    text: "Briskpace"
    code: "Roboto Mono Medium"
  features:
    - content.code.copy
    - content.code.annotate
  # Setup for theme switch https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
plugins:
   - glightbox

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - assets/extra.css

nav:
- About: 'index.md'
- Blog:
  - Books:
    - Ghost Radio: 'blog/books/ghost-radio.md'
- Data Structures:
  - Numbers:
    - Representation: 'data-structures/numbers/representation.md'
    - Arithmetic: 'data-structures/numbers/arithmetic.md'
  - Linked List:
    - Basics: 'data-structures/linked-list/basics.md'
    - Reversing linked list: 'data-structures/linked-list/reverse.md'
    - Sentinel: 'data-structures/linked-list/sentinel.md'
    - Linked list as Stack: 'data-structures/linked-list/stack-as-linked-list.md'
    - Linked list as Queue: 'data-structures/linked-list/queue-as-linked-list.md'
    - Iterate over list: 'data-structures/linked-list/iterate.md'
    - Compare linked lists: 'data-structures/linked-list/equality.md'
    - Clone linked lists: 'data-structures/linked-list/clone.md'
    - Merge linked lists: 'data-structures/linked-list/merge.md'
    - Circular linked list: 'data-structures/linked-list/circular-linked-list.md'
  - Stack:
    - Basics: 'data-structures/stack/basics.md'
  - Heap: 'data-structures/heap/index.md'
  - Circular list: 'data-structures/circular-list.md'
  - Graph:
    - Intro: 'data-structures/graph/intro.md'
    - Traversal:
        - Generic Search: 'data-structures/graph/generic-search.md'
        - BFS: 'data-structures/graph/bfs.md'
        - DFS: 'data-structures/graph/dfs.md'
    - Topological Sort: 'data-structures/graph/topological-sort.md'
- Algorithms:
  - Binary Search: 'algorithms/search/binary.md'
  - Partitioning: 'algorithms/partition/partition.md'
  - Sorting:
    - Quicksort: 'algorithms/sort/quicksort.md'
    - Mergesort: 'algorithms/sort/mergesort.md'
- Design Patterns:
  - Creational:
    - Singleton: 'design-patterns/singleton.md'
    - Builder: 'design-patterns/builder.md'
- Concurrency:
  - Intro: 'concurrency/intro.md'
- Java:
  - Collections: 'java/collections-framework.md'
  - Iterators: 'java/iterators.md'
- Kotlin:
  - Concurrency: 'kt/concurrency.md'
- Android:
  - Activities: 'android/activities.md'
  - Tasks: 'android/tasks.md'
  - Fragments: 'android/fragments.md'
  - Animations: 'android/animation-transition.md'
- Javascript:
  - Objects:
    - Basics: 'js/objects/basics.md'
    - Prototype: 'js/objects/prototype.md'
    - this: 'js/objects/this.md'
- CSS:
  - Box Model: 'css/box-model.md'
  - em, rem, and more: 'css/relative-units.md'
- Python:
  - Basics: 'python/basics.md'
  - Operators: 'python/operators.md'
  - Structure: 'python/structure.md'
  - Objects: 'python/objects.md'
  - Functions: 'python/functions.md'
  - Generators: 'python/generators.md'
  - Object Oriented Programming: 'python/oop.md'
- Ubuntu:
  - Setup: 'ubuntu/setup.md'
- Miscellaneous:
  - Display Upgrade: 'misc/display.md'



